name: kazoo-configs-core
custom_files: null
exposure: private
base_branch: origin/master
base_core: null
template: spec.tmpl
package:
  centos7:
    name: kazoo-sounds
    group: Productivity/Telephony
    license: MPL1.1
    build_arch: noarch
    build_requires:
      - rpm-build
    summary: 'Audio files for the Kazoo platform'
    description: |
      Audio files for the various components that make up the Kazoo platform.
    dist: .el7.centos
    requires:
      sudo: {  }
    source: '%{_build_tar}'
    prep: '%setup -q'
    install: |
      %{__mkdir} -p %{buildroot}/usr/share/kazoo-freeswitch/sounds
      %{__mkdir} -p %{buildroot}/opt/kazoo/sounds
      find freeswitch/ -mindepth 1 -maxdepth 1 -type d -exec cp -a {} %{buildroot}/usr/share/kazoo-freeswitch/sounds \;
      find kazoo-core/ -mindepth 1 -maxdepth 1 -type d -exec cp -a {} %{buildroot}/opt/kazoo/sounds \;
    files: null
    url: 'http://www.2600hz.org'
    vendor: 2600Hz
  rockylinux8:
    name: kazoo-sounds
    group: Productivity/Telephony
    license: MPL1.1
    build_arch: noarch
    build_requires:
      - rpm-build
    summary: 'Audio files for the Kazoo platform'
    description: |
      Audio files for the various components that make up the Kazoo platform.
    dist: .el8
    requires:
      sudo: {  }
    source: '%{_build_tar}'
    prep: '%setup -q'
    install: |
      %{__mkdir} -p %{buildroot}/usr/share/kazoo-freeswitch/sounds
      %{__mkdir} -p %{buildroot}/opt/kazoo/sounds
      find freeswitch/ -mindepth 1 -maxdepth 1 -type d -exec cp -a {} %{buildroot}/usr/share/kazoo-freeswitch/sounds \;
      find kazoo-core/ -mindepth 1 -maxdepth 1 -type d -exec cp -a {} %{buildroot}/opt/kazoo/sounds \;
    files: null
    url: 'http://www.2600hz.org'
    vendor: 2600Hz
  rockylinux9:
    name: kazoo-sounds
    group: Productivity/Telephony
    license: MPL1.1
    build_arch: noarch
    build_requires:
      - rpm-build
    summary: 'Audio files for the Kazoo platform'
    description: |
      Audio files for the various components that make up the Kazoo platform.
    dist: .el9
    requires:
      sudo: {  }
    source: '%{_build_tar}'
    prep: '%setup -q'
    install: |
      %{__mkdir} -p %{buildroot}/usr/share/kazoo-freeswitch/sounds
      %{__mkdir} -p %{buildroot}/opt/kazoo/sounds
      find freeswitch/ -mindepth 1 -maxdepth 1 -type d -exec cp -a {} %{buildroot}/usr/share/kazoo-freeswitch/sounds \;
      find kazoo-core/ -mindepth 1 -maxdepth 1 -type d -exec cp -a {} %{buildroot}/opt/kazoo/sounds \;
    files: null
    url: 'http://www.2600hz.org'
    vendor: 2600Hz
metapackage:
  -
    name: meta-kazoo-applications
    package: kazoo-sounds-core-en-us
    type: required
    branch: '5.0'
  -
    name: meta-kazoo-applications
    package: kazoo-sounds-core-es-es
    type: required
    branch: '5.0'
  -
    name: meta-kazoo-applications
    package: kazoo-sounds-core-fr-ca
    type: required
    branch: '5.0'
  -
    name: meta-kazoo-applications
    package: kazoo-sounds-core-ru-ru
    type: required
    branch: '5.0'
  -
    name: meta-kazoo-freeswitch
    package: kazoo-sounds-freeswitch-en-us
    type: required
    branch: '5.0'
  -
    name: meta-kazoo-freeswitch
    package: kazoo-sounds-freeswitch-fr-ca
    type: required
    branch: '5.0'
  -
    name: meta-kazoo-freeswitch
    package: kazoo-sounds-freeswitch-music-8000
    type: required
    branch: '5.0'
  -
    name: meta-kazoo-freeswitch
    package: kazoo-sounds-freeswitch-ru-ru
    type: required
    branch: '5.0'
dependencies: null
